rules:
  - id: private-method-environment-variable-dependency
    patterns:
      - pattern-inside: |
          private
          ...
          def $M(...)
            ...
          end
      - pattern-either:
          - pattern: ENV[$KEY]
          - pattern: ENV.fetch($KEY, ...)
      - focus-metavariable: $KEY
    message: |
      Don't reference environment variables inside private methods,
      as this creates a dependency on them.
    languages:
      - ruby
    severity: ERROR
