# frozen_string_literal: true

source "https://rubygems.org"

gem "pronto", "~> 0.11.1"
gem "faraday-retry", "~> 2.1"
gem "rubocop-rspec", "~> 2.20"
gem "pronto-rubocop", "~> 0.11.5"
gem "pronto-erb_lint", "~> 0.1.6"
# gem "pronto-fasterer", "~> 0.11.2"
