# frozen_string_literal: true

source "https://rubygems.org"

gem "pronto", "~> 0.11.1"
gem "faraday-retry", "~> 2.1"
gem "rubocop-rails", "~> 2.19"
gem "rubocop-rspec", "~> 2.20"
gem "pronto-rubocop", "~> 0.11.5"
gem "pronto-erb_lint", "~> 0.1.6"
gem "pronto-yamllint", "~> 0.2.0"
gem "pronto-scss", "~> 0.11.0"
gem "pronto-brakeman", "~> 0.11.2"
# gem "pronto-fasterer", "~> 0.11.2"
