env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
plugins:
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
ignorePatterns:
  - "**/vendor/assets/javascripts/*.js"
  - "**/vendor/assets/**/*.js"
rules:
  prettier/prettier: error
  no-undef: warn
  no-unused-vars:
    - "error"
    - argsIgnorePattern: "^_"
      vars: "local"
globals:
  "$": "readonly"
  "Rails": "readonly"
