env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
plugins:
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  prettier/prettier: error
  no-undef: warn
  no-unused-vars:
    - warn
    - argsIgnorePattern: "^_"
globals:
  "$": "readonly"
  "Rails": "readonly"
