require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisabledByDefault: true

  Exclude:
    - !ruby/regexp /db\/schema\.rb/

inherit_from:
  - rubocop/Layout.yml
  - rubocop/Style.yml
  - rubocop/Lint.yml
  - rubocop/Rails.yml
  - rubocop/RSpec.yml
