extends: default

ignore:
  - "**/spec/support/cassettes"

rules:
  line-length:
    max: 120

  comments:
    level: error

  truthy:
    allowed-values:
      - "true"
      - "false"
      - "on"

  document-start: disable
