name: Lint

on:
  workflow_call:

jobs:
  dotenv-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3

      - name: Install dotenv-linter
        run: |
          curl \
            --retry 5 \
            --retry-max-time 120 \
            --retry-connrefused \
            --retry-all-errors \
            --output /tmp/install.sh \
            'https://raw.githubusercontent.com/dotenv-linter/dotenv-linter/master/install.sh'
          sh /tmp/install.sh

      - name: dotenv-linter
        run: bin/dotenv-linter --skip UnorderedKey --skip QuoteCharacter .env*
