name: Lint

on:
  workflow_call:

jobs:
  dotenv-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3

      - name: Install dotenv-linter
        run: curl -sSfL https://git.io/JLbXn | sh -s

      - name: dotenv-linter
        run: bin/dotenv-linter --skip UnorderedKey --skip QuoteCharacter .env*
