name: RSpec

on:
  workflow_call:
    inputs:
      package_dependencies:
        required: false
        type: string
        default: ""

jobs:
  rspec:
    runs-on: ubuntu-latest

    steps:
      - name: "Install Package Dependencies"
        if: ${{ inputs.package_dependencies != '' }}
        run: sudo apt-get install --yes --quiet ${{ inputs.package_dependencies }}

      #######################################################################
      # RSpec
      #######################################################################

      # https://github.com/actions/checkout#checkout-multiple-repos-side-by-side
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          path: ${{ github.repository }}

      - name: Setup Ruby for ${{ github.repository }}
        uses: ruby/setup-ruby@v1
        with:
          working-directory: ${{ github.repository }}
          bundler-cache: true

      - name: RSpec
        working-directory: ${{ github.repository }}
        run: bundle exec rspec
